<a href="https://colab.research.google.com/github/GaryPython/Data-science-marathon/blob/main/%E4%BD%9C%E6%A5%ADD06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [2]:
import numpy as np


In [3]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [13]:
np.savez('work_array.npz', array1=array1, array2=array2)

In [14]:
npzfile = np.load('work_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [15]:
npzfile.files

['array1', 'array2']

In [27]:
npzfile['array1']


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
npzfile['array2']

array([2, 3, 5])

In [16]:
print(npzfile['array1'])
print(npzfile['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [ ]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [17]:
array3 = np.array([[4,5,6],[1,2,3]])

In [29]:
load_array = np.load('work_array.npz')
np.savez('new_work_array.npz',npzfile['array1'],npzfile['array2'],array3)

In [20]:
!ls

new_work_array.npz  sample_data  work_array.npz


In [30]:
new_npzfile = np.load('new_work_array.npz')
type(new_npzfile)

numpy.lib.npyio.NpzFile

In [31]:
new_npzfile.files

['arr_0', 'arr_1', 'arr_2']

In [33]:
print(new_npzfile['arr_0'])
print(new_npzfile['arr_1'])
print(new_npzfile['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
